/**
 * Core type definitions for the Golf Cart Configurator system.
 * 
 * Architecture note: These types form the foundation of the entire application.
 * All configuration state, pricing calculations, and 3D scene updates flow from
 * these strongly-typed definitions. Changes here ripple throughout the system.
 */

/**
 * Unique identifier for cart platform versions.
 * Future: Will support multiple cart platforms (street legal, off-road, etc.)
 */
export type PlatformId = string;

/**
 * Unique identifier for configuration options.
 */
export type OptionId = string;

/**
 * Unique identifier for material definitions.
 */
export type MaterialId = string;

/**
 * Unique identifier for saved configurations.
 */
export type ConfigurationId = string;

/**
 * Material zones define which part of the cart accepts material customization.
 */
export enum MaterialZone {
  BODY = 'BODY',
  SEATS = 'SEATS',
  ROOF = 'ROOF',
  METAL = 'METAL',
  GLASS = 'GLASS'
}

/**
 * Material types define the application method.
 */
export enum MaterialType {
  PAINT = 'PAINT',
  VINYL = 'VINYL',
  POWDERCOAT = 'POWDERCOAT',
  FABRIC = 'FABRIC',
  TINT = 'TINT'
}

/**
 * Material finish affects appearance and pricing.
 */
export enum MaterialFinish {
  GLOSS = 'GLOSS',
  MATTE = 'MATTE',
  SATIN = 'SATIN',
  METALLIC = 'METALLIC'
}

/**
 * Option categories organize the configuration UI and rules engine.
 */
export enum OptionCategory {
  SEATING = 'SEATING',
  ROOF = 'ROOF',
  WHEELS = 'WHEELS',
  LIGHTING = 'LIGHTING',
  STORAGE = 'STORAGE',
  ELECTRONICS = 'ELECTRONICS',
  SUSPENSION = 'SUSPENSION',
  FABRICATION = 'FABRICATION'
}

/**
 * Material definition with pricing and physical properties.
 */
export interface Material {
  id: MaterialId;
  zone: MaterialZone;
  type: MaterialType;
  name: string;
  description: string;
  color: string; // hex color code
  finish: MaterialFinish;
  priceMultiplier: number; // multiplier against base zone price
}

/**
 * Configuration option with constraints and pricing.
 * 
 * Architecture note: The requires/excludes arrays drive the rules engine.
 * These constraints are evaluated before allowing option selection.
 */
export interface ConfigOption {
  id: OptionId;
  category: OptionCategory;
  name: string;
  description: string;
  partPrice: number; // cost of parts in USD
  laborHours: number; // estimated labor time
  requires: OptionId[]; // options that must be selected first
  excludes: OptionId[]; // options that cannot coexist
  assetPath: string; // path to 3D model (placeholder for now)
}

/**
 * Represents the selected material for a specific zone.
 */
export interface MaterialSelection {
  zone: MaterialZone;
  materialId: MaterialId;
}

/**
 * Complete cart configuration state.
 * 
 * Architecture note: This is the single source of truth for the entire
 * configurator. It must be serializable for saving/loading and drive
 * both the 3D scene and pricing engine deterministically.
 */
export interface CartConfiguration {
  id: ConfigurationId;
  platformId: PlatformId;
  selectedOptions: OptionId[];
  materialSelections: MaterialSelection[];
  buildNotes: string;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Itemized price breakdown for a single option.
 */
export interface PriceLineItem {
  optionId: OptionId;
  optionName: string;
  category: OptionCategory;
  partsCost: number;
  laborCost: number;
  totalCost: number;
}

/**
 * Itemized price breakdown for a material selection.
 */
export interface MaterialPriceLineItem {
  zone: MaterialZone;
  materialId: MaterialId;
  materialName: string;
  cost: number;
}

/**
 * Complete pricing breakdown for a configuration.
 * 
 * Architecture note: Generated by the pricing engine as a pure function
 * of CartConfiguration + option definitions + material definitions.
 * Must be deterministic and independently testable.
 */
export interface PricingBreakdown {
  configurationId: ConfigurationId;
  basePlatformPrice: number;
  optionLineItems: PriceLineItem[];
  materialLineItems: MaterialPriceLineItem[];
  subtotal: number;
  laborTotal: number;
  grandTotal: number;
}

/**
 * Quote request submitted by a customer.
 */
export interface QuoteRequest {
  configurationId: ConfigurationId;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  message: string;
  submittedAt: Date;
}

/**
 * Quote record with status tracking.
 */
export interface Quote {
  id: string;
  configurationId: ConfigurationId;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  message: string;
  status: QuoteStatus;
  submittedAt: Date;
}

/**
 * Quote lifecycle status.
 */
export enum QuoteStatus {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  QUOTED = 'QUOTED',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED'
}

/**
 * Platform definition (base cart model).
 */
export interface Platform {
  id: PlatformId;
  name: string;
  description: string;
  basePrice: number;
  defaultAssetPath: string;
}

/**
 * Validation result for configuration rules.
 */
export interface ValidationResult {
  valid: boolean;
  errors: string[];
}
